---
title: "Tracked fish CTRL"
author: "Simo"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# load(file = "~/calcium-clustering/14012024.RData")
library(pacman)
p_load(utils, dplyr, tidyverse, ggplot2, plotly, tidyr, reshape2, factoextra, ggdendro,
       grid, RcppCNPy, cowplot, ggpubr, mmand, rstudioapi, reticulate, tcltk, ggfortify,
       ggpubr, factoextra, parallel, ggpattern, ggsignif, car, gtools)
load(file = "15012024.RData")
```
# Control VS AKT1
### Mean Calcium Levels
```{r CTRL vs AKT1 vs HRASV12 Mean Calcium all cells, echo=FALSE, warning=FALSE}
CTRL_AKT1_HRASV12_mean_Ca_merged_data.df.plt
```

### Frequency as events/min
```{r CTRL vs AKT1 vs HRASV12 Frequency of events/min all cells, echo=FALSE, warning=FALSE}
CTRL_AKT1_HRASV12_frequency_merged_data.df.plt
```

Clustering Coefficients are parallel until 8dpf, where CTRL increases while AKT1 stalls
```{r Clustering Coefficients, echo=FALSE, warning=FALSE}
CTRL_AKT1_HRASV12.clustcoeff_merged_data.df.plt
```
Global Efficiency
```{r Global Efficiency, echo=FALSE, warning=FALSE}
CTRL_AKT1_HRASV12.globaleff_merged_data.df.plt
```
Small worldness
```{r Small-worldness, echo=FALSE}

```



# RFP cells comparisons
```{r Mean Ca in RFP cells}
CTRL_mean_Ca.RFP_comparison
AKT1_mean_Ca.RFP_comparison
HRASV12_mean_Ca.RFP_comparison
CTRL_AKT1_HRASV12_mean_Ca.RFP.plt
```

```{r Mean Clustering Coefficients in RFP cells only}
CTRL_AKT1_HRASV12.clustcoeff.RFP.df.plt
```

